### ISSUE TITLE
環境構築手順書を作成する

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sveltekit_authentication_example#35]
- [x] 他の package を参考にする。
- [x] README.md を書き換える。
- [x] プロジェクト名に example をつける。

**Comment by AtsushiUtsumi** [comment]
github から cloneしてくる
npm install 
install mysql-server mysql-client

データベース作成

質問
ユーザーの作成はするのか?
権限の設定は Prisma の仕事?

Roleに以下を追加
admin
user


.env.example
をコピーして編集して「.env」を作成
.env dbのurlを書き換え

ターミナルで以下のコマンドを実行
npx prisma db push
npx prisma studio

role table 開く

admin user　追加
